/// Flutter icons AppIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
///
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const dynamic _kFontPkg = null;

  static const IconData ic_profile = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_358 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watermelon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_home_1 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_call = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___right = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData appointment = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bmi = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cell_phone = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dish = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData goal = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightbulb = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData measurement = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData muscle_flex_outline = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pear = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trans_fat = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight_scale = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_orders = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_user = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_password = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_alt = IconData(0xf510, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
